# Generated by Django 3.0.3 on 2020-06-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
